### ISSUE TITLE
Issue with version 1.4.2

### ISSUE THREAD

**Issue by hamedvakilit** [wannier-berri/wannier-berri#425]
Dear developers,

I tried read the system from wannier90 using wannierberri version 1.4.2, It works fine with version 1.3.0: 
system_QE=wberri.System_w90(
                        seedname='test',
                        berry=True,
                        spin = True ,
                        );
I get error:
File ~/.venv/.venv/lib/python3.12/site-packages/wannierberri/system/system_w90.py:145, in System_w90.__init__(self, seedname, w90data, transl_inv_MV, transl_inv_JM, fftlib, npar, wannier_centers_from_chk, read_npz, write_npz_list, write_npz_formatted, overwrite_npz, formatted, symmetrize, **parameters)
    143         _needed_files.update(needed_files[key])
    144     _needed_files = list(_needed_files)
--> [145] (python3.12/site-packages/wannierberri/system/system_w90.py:145)     w90data = Wannier90data().from_w90_files(
    146         self.seedname,
    147         write_npz_list=write_npz_list, read_npz=read_npz, overwrite_npz=overwrite_npz,
    148         readfiles=_needed_files,
    149         write_npz_formatted=write_npz_formatted,
    150         formatted=formatted)
    151     # w90data.set_chk(kmesh_tol=kmesh_tol, bk_complete_tol=bk_complete_tol, read=True)
    152 w90data.check_wannierised(msg="creation of System_w90")
...
---> [78] (python3.12/site-packages/wannierberri/io.py:78)     return cls(**dic_loc)
     79 else:
     80     return dic_loc

TypeError: MMN.__init__() missing 3 required positional arguments: 'bk_latt', 'bk_cart', and 'wk'

Without berry and spin gives error:

File ~/.venv/.venv/lib/python3.12/site-packages/wannierberri/system/system_w90.py:145, in System_w90.__init__(self, seedname, w90data, transl_inv_MV, transl_inv_JM, fftlib, npar, wannier_centers_from_chk, read_npz, write_npz_list, write_npz_formatted, overwrite_npz, formatted, symmetrize, **parameters)
    143         _needed_files.update(needed_files[key])
    144     _needed_files = list(_needed_files)
--> [145] (python3.12/site-packages/wannierberri/system/system_w90.py:145)     w90data = Wannier90data().from_w90_files(
    146         self.seedname,
    147         write_npz_list=write_npz_list, read_npz=read_npz, overwrite_npz=overwrite_npz,
    148         readfiles=_needed_files,
    149         write_npz_formatted=write_npz_formatted,
    150         formatted=formatted)
    151     # w90data.set_chk(kmesh_tol=kmesh_tol, bk_complete_tol=bk_complete_tol, read=True)
    152 w90data.check_wannierised(msg="creation of System_w90")
...
---> [33] (python3.12/site-packages/wannierberri/w90files/w90file.py:33) assert NK is not None, "NK must be provided if data is a dictionary"
     34 self.data = data
     35 self.NK = NK

AssertionError: NK must be provided if data is a dictionary

Best,
Hamed

**Comment by stepan-tsirkin** [comment]
Yes, older npz files are not compatible with newer version. Just remove the old ones, and newer files will be written.
